[package]
name = "stft"
version = "0.0.3"
edition = "2021"

[dependencies]
num-complex = "0.4.5"
num-traits = "0.2.18"
rustfft = "6.2.0"
rayon = "1.10"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
